### ISSUE TITLE
希望能够在卡片的3D图上叠加一些元素

### ISSUE THREAD

**Issue by Seifon** [FrostZhang/hass_unity_home#7]
比如通过下面的配置，就能在3D界面周围放一个时间，或者其它图标等元素：
```
type: custom:scene3d-card
elements:
  - type: image
    entity: switch.deng_pao
    tap_action: none
    hold_action: none
    state_image:
      'on': >-
        /local/TileBoard-a1650a1d-84e2-0ff7-cb75-6a76b171076d/images/tile-screenshots/ALARM.png
      'off': >-
        /local/TileBoard-a1650a1d-84e2-0ff7-cb75-6a76b171076d/images/tile-screenshots/ALARM.png
      unavailable: >-
        /local/TileBoard-a1650a1d-84e2-0ff7-cb75-6a76b171076d/images/tile-screenshots/ALARM.png
    style:
      top: 50%
      left: 50%
      width: 100%
```

就跟下面这张图差不多，能够看时间，能够放置一些其它按钮和卡片：
![img](https://bbs.hassbian.com/data/attachment/forum/202206/11/144335hq0kp0gq08pgigke.png)
